### PR TITLE
Fix: behavior incompatiblity between (standalone) LS and LS in Docker

### LINKED ISSUE #29: plugin behavior difference in Docker vs non-Docker env
**Logstash information**: 7.15.2

**Plugin version: 3.3.3**

**OS version** (`uname -a` if on a Unix-like system): `5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

In the case a command to execute is missing, one expects `ENOENT` system error :
`Errno::ENOENT: No such file or directory - invalid_command for a missing command`,

however the behavior is different in Docker - popen does not raise - we simply get a non-zero exit code:
`"message"=>"", "process"=>{"command_line"=>"invalid_command 1 2 3", "exit_code"=>127}`

**Steps to reproduce**:

```ruby
input {
  exec {
    command => "invalid_command 1 2 3"
    intrerval => 0
  }
}

output { stdout {} }
```

Run the above configuration (on a Linux/Mac) using Logstash vs Logstash in docker.

### PR DESCRIPTION
**Pull request by kares**
**Description of the problem including expected versus actual behavior (from #29)**:

> In the case a command to execute is missing, one expects `ENOENT` system error :
`Errno::ENOENT: No such file or directory - invalid_command for a missing command`,

> however the behavior is different in Docker - popen does not raise - we simply get a non-zero exit code:
`"message"=>"", "process"=>{"command_line"=>"invalid_command 1 2 3", "exit_code"=>127}`

---
PENDING suggestion from https://github.com/logstash-plugins/logstash-input-exec/pull/28#discussion_r747712250 :

> If there are two different behaviours, depending on which platform it is run, I would prefer we clearly specify both behaviours instead of specifying one of the behaviours and conditionally executing that spec.

> If possible, it could be helpful to _emulate_ the underlying change in behaviour and define our specs so that we can validate our effective behavour in CI regardless of which platform it is executed on (It would be hard to stub `IO::popen` because we rely on its side-effect of setting `$?`, but can we stub `run_command`?).

> So our specs output would look something like:

 - `when command fails`
   - `on a platform where IO.popen raises ENOENT`
     - `it does not enqueue an event`
   - `on a platform where IO.popen does not raise ENOENT (Docker)`
     - `it enqueues an event tagged with the error code`
---

**Ideally we would rather want the same behavior in Docker vs non-Docker LS ...**

By switching to `Open3`'s `popen` the behavior is now consistent between LS in Docker and standalone LS.

Previously, when a user would run Docker-ized LS using the exec input and points to a wrong/missing executable to run, the plugin would generates (error) events with a non-zero exit status (`127`), in standalone mode no events would have been generated.

### CODE REVIEW

File: lib/logstash/inputs/exec.rb [hunk 1]
```diff
@@ -105,20 +105,24 @@ def execute(queue)
...
 
-  # Close @io
-  def close_io
-    return if @io.nil? || @io.closed?
-    @io.close
-    @io = nil
+  def do_close(io)
+    return if io.nil? || io.closed?
+    io.close
   end
```
Comment (jsvd) [inline lib/logstash/inputs/exec.rb]: Maybe we can just guard this step against some last minute broken pipes or any other errors from closing an IO object? Something like

```suggestion
  def do_close(io)
    return if io.nil? || io.closed?
    io.close
  rescue => e
    @logger.debug("exception raised while closing io. ignoring..", :io => io, :exception => e.class, :message => e.message)
  end
```

**Comment by kares** [comment]
CI :red_circle: only happens on 8.x SNAPSHOT and seems to be caused by https://github.com/elastic/logstash/issues/13572 (further investigation needed)
